<?xml version="1.0"?><!DOCTYPE note [<!ELEMENT details (id, title, series_name, episode_name, season_number, episode_number, firstaired, genre, runtime, director, actor, overview)><!ELEMENT id (#PCDATA)><!ELEMENT title (#PCDATA)><!ELEMENT series_name (#PCDATA)><!ELEMENT episode_name (#PCDATA)><!ELEMENT season_number (#PCDATA)><!ELEMENT episode_number (#PCDATA)><!ELEMENT firstaired (#PCDATA)><!ELEMENT genre (#PCDATA)><!ELEMENT runtime (#PCDATA)><!ELEMENT director (#PCDATA)><!ELEMENT actor (#PCDATA)><!ELEMENT overview (#PCDATA)>]>
<details>
  <id>4130005</id>
  <title>104: Rosetta</title>
  <series_name>Alphas</series_name>
  <episode_name>Rosetta</episode_name>
  <season_number>1</season_number>
  <episode_number>4</episode_number>
  <firstaired>2011-08-01</firstaired>
  <genre>Alphas</genre>
  <runtime>N/A</runtime>
  <director>Karen Gaviola</director>
  <actor>Warren Christie/Laura Mennell/Azita Ghanizada/David Strathairn/Ryan Cartwright/Malik Yoba/Erin Way/Mahershala Ali</actor>
  <overview>The Alpha team closes in on Red Flag and rescues an autistic woman, Anna, with the ability to translate any language. The team tries to figure out Red Flagâ€™s plan while Gary bonds with Anna.</overview>
</details>
